name: ecoteam_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  fl_chart: ^1.0.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  intl_phone_field: ^3.2.0
  intl: ^0.18.0
  file_selector: ^1.0.3
  permission_handler: ^11.3.1
  #file_selector: ^5.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.2
  provider: ^6.0.5
  image_picker: ^1.0.7
  uuid: ^4.2.2
  open_file: ^3.5.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loginanimation.json
    - assets/
