// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV9Iv3FihVeq0YKQ6ksLTQzExOzuwJbUo',
    appId: '1:149840621362:web:2e28cc5e3351e18376b12b',
    messagingSenderId: '149840621362',
    projectId: 'sitepilot-a003c',
    authDomain: 'sitepilot-a003c.firebaseapp.com',
    storageBucket: 'sitepilot-a003c.firebasestorage.app',
    measurementId: 'G-B49RFSFXEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBRXARf5YobhbSC089iU8li3YEt9AwDCw',
    appId: '1:149840621362:android:0e791819aeecdc3276b12b',
    messagingSenderId: '149840621362',
    projectId: 'sitepilot-a003c',
    storageBucket: 'sitepilot-a003c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf-d-uOpCFx2o3VGtR4LuiJH99VSHQ1UQ',
    appId: '1:149840621362:ios:7262ec40f96f350c76b12b',
    messagingSenderId: '149840621362',
    projectId: 'sitepilot-a003c',
    storageBucket: 'sitepilot-a003c.firebasestorage.app',
    iosBundleId: 'com.easy2it.sitepilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf-d-uOpCFx2o3VGtR4LuiJH99VSHQ1UQ',
    appId: '1:149840621362:ios:9faa8f487da078aa76b12b',
    messagingSenderId: '149840621362',
    projectId: 'sitepilot-a003c',
    storageBucket: 'sitepilot-a003c.firebasestorage.app',
    iosBundleId: 'com.example.ecoteamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV9Iv3FihVeq0YKQ6ksLTQzExOzuwJbUo',
    appId: '1:149840621362:web:74493aaca63a2e7076b12b',
    messagingSenderId: '149840621362',
    projectId: 'sitepilot-a003c',
    authDomain: 'sitepilot-a003c.firebaseapp.com',
    storageBucket: 'sitepilot-a003c.firebasestorage.app',
    measurementId: 'G-96HDS45SZY',
  );
}
